# Generated by Django 5.0.7 on 2024-07-30 07:39

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20200324_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='musician_images'),
            preserve_default=False,
        ),
    ]
