# Generated by Django 5.0.7 on 2024-07-30 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_musician_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, default='default_musician.jpg', null=True, upload_to='musician_images'),
        ),
    ]
