# Generated by Django 5.0.7 on 2024-07-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_alter_musician_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='image',
            field=models.ImageField(default='media/default_musician.jpg', upload_to='media/'),
        ),
    ]
