# Generated by Django 5.0.7 on 2024-07-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_alter_musician_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='image',
        ),
    ]
