# Generated by Django 5.0.7 on 2024-07-30 18:31

import first_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_remove_musician_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='image',
            field=models.ImageField(blank=True, storage=first_app.models.DefaultImageStorage(), upload_to='musicians/'),
        ),
    ]
